do_chore:
  name: "Do Chore"
  description: "Marks the chore as done and updates points and next due."
  fields:
    entity_id:
      description: "The entity id of the chore."
      example: "sensor.take_out_trash"
    helper_number:
      description: "The Number you want to increase the points to (Optional)"
      example: "input_number.chore_points"

set_last_done:
  name: "Set Last Done"
  fields:
    entity_id:
      example: "sensor.take_out_trash"
    value:
      description: "Datetime in ISO format."
      example: "2025-10-07T12:00:00"

set_next_due:
  name: "Set Next Due"
  fields:
    entity_id:
      example: "sensor.take_out_trash"
    value:
      description: "Datetime in ISO format."
      example: "2025-10-10T12:00:00"

set_days:
  name: "Set Days"
  fields:
    entity_id:
      example: "sensor.take_out_trash"
    value:
      description: "Number of days between chores."
      example: 7

set_points:
  name: "Set Points"
  fields:
    entity_id:
      example: "sensor.take_out_trash"
    value:
      description: "Number of points for this chore."
      example: 5
